# config/packages/security.yaml
security:
    enable_authenticator_manager: true
    # ...
    password_hashers:
        App\Entity\User: 'auto'
    providers:
        users:
            entity:
                # the class of the entity that represents users
                class: 'App\Entity\User'
                # the property to query by - e.g. email, username, etc
                property: 'email'

                # optional: if you're using multiple Doctrine entity
                # managers, this option defines which one to use
                #manager_name: 'customer'

    # ...   
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        registration:
            pattern: ^/api/users
            stateless: true
            methods : [POST,get]  # ... permet de ne laisser public que la method post
            
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: IS_AUTHENTICATED_FULL,methods : [PUT,DELETE,PATCH] }
        - { path: ^/api/demo,  roles: IS_AUTHENTICATED_FULLY }